### ISSUE TITLE
Syntax Highlighting Improvement

### ISSUE THREAD

**Issue by e0lithic** [vhda/verilog_systemverilog.vim#133]
Since tags are already being used, could it be possible to highlight the classes (which have been already declared) at the time of instantiation or object creation? For eg.

Class a;
Endclass

Class b;
**_a_** a1;
function new();
   a1 = **_a_**::type_id::create("a1");
endfunction;
endclass

**Comment by vhda** [comment]
I consider that functionality outside the scope of this plugin, because there are already many plugins doing that.

For example, two that I've just found:

* [Easytags](https://github.com/xolox/vim-easytags) - also maintains tag database automatically.
* [TagHighlight](https://github.com/vim-scripts/TagHighlight) - screenshots look nice, I should try it sometime.

Please do share which plugin you end up using.

**Comment by vhda** [comment]
@eolithic did you end up testing any of these plugins?

**Comment by vhda** [comment]
@eolithic any updates?

**Comment by vhda** [comment]
Closing issue.
Please feel free to re-open if you feel that my answer was not sufficient.
